### ISSUE TITLE
Python2 exception if byte-encoded unicode is passed to FileSequence constructor

### ISSUE THREAD

**Issue by justinfx** [justinfx/fileseq#100]
If a unicode string is encoded to bytes and then passed into a `FileSequence` constructor, the str/repr handling will fail in Python2

```python
    def testStrUnicode(self):
        ret = FileSequence(u'file_カ_Z.01.txt')
        # make sure none of these raise a unicode exception
        _ = str(ret)
        _ = text_type(ret)
        _ = repr(ret)
        _ = ret.format()

        if PY2:
            # only test this in py2 since we don't accept bytes
            # in python3+
            ret = FileSequence(u'file_カ_Z.01.txt'.encode('utf-8'))
            # make sure none of these raise a unicode exception
            _ = str(ret)
            _ = text_type(ret)
            _ = repr(ret)
            _ = ret.format()
```

```
    def __str__(self):
        """
        String representation of this :class:`FileSequence`.
    
        Returns:
            str:
        """
        frameSet = utils.asString(self._frameSet or "")
        return "".join((
            self._dir,
            self._base,
            frameSet,
            self._pad if frameSet else "",
>           self._ext))
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 5: ordinal not in range(128)
```

Need to ensure that `__str__` returns a unicode object as needed, if python2

Refs #99 as some of the initial work on python2 unicode improvements

**Comment by GlenWalker** [comment]
It's worth noting that we should probably use sys.getfilesystemencoding() when converting paths between bytes and unicode in Python 2, since file sequences are implicitly paths - fileseq.utils.asString currently hardcodes 'utf-8'.

Note also that in some embedded interpreters sys.getfilesystemencoding() will return None, so I generally do something like:
`FILESYSTEM_ENCODING = sys.getfilesystemencoding() or 'utf-8'`

Later versions of Python have `os.fsencode` and `os.fsdecode`, which also handles surrogateescape if bytes are not valid UTF-8, as can happen in practice on the filesystem because filesystem encoding is not enforced in Linux)

**Comment by justinfx** [comment]
Sounds good, @GlenWalker. I will go with that filesystem encoding constant. Hopefully that will be enough to keep python2 working until it can eventually be dropped.
