### ISSUE TITLE
findSequenceOnDisk() failing on this particular sequence

### ISSUE THREAD

**Issue by ogre** [justinfx/fileseq#110]
So I have a sequence that findSequenceOnDisk () seems to fail on:

```
touch ./A001C009_220324BV_924360.tga
touch ./A001C009_220324BV_924361.tga
touch ./A001C009_220324BV_924362.tga

```

Then in python:

```
import fileseq
fileseq.findSequenceOnDisk('./A001C009_220324BV_924360.tga').frameRange() #returns empty
'' 
```

Can anybody please confirm ?

**Comment by justinfx** [comment]
`findSequencesOnDisk` does take a different code path than `findSequenceOnDisk`, where the latter basically starts out by passing your pattern directly to the `FileSequence()` constructor. This is where the difference in behaviour happens, because the `FileSequence` class ends up determining the pattern represents just a single file and not a sequence, and it sets the basename to "A001C009_220324BV_924360", and the frame range to empty. That happens because after first attempt to parse a pattern fails, it falls back on checking whether the basename ends with a ".". As it does not end in a period (it ends in underscore) it just assumes its a single file.

I will go ahead and close this ticket since it seems you found a working solution using `findSequencesOnDisk`. With that approach, you can always reference the basename of the sequence, if it returns more than one.
