### ISSUE TITLE
FileSequence.findSequenceOnDisk changes padding style unless called with strictPadding=True

### ISSUE THREAD

**Issue by herronelou** [justinfx/fileseq#112]
`FileSequence.findSequenceOnDisk('/path/to/file.$F.exr')` returns a FileSequence with padding '#' instead of '$F'.

It seems like it would be fine without the `and strictPadding` on https://github.com/justinfx/fileseq/blob/master/src/fileseq/filesequence.py#L1123

according to the docstring for strictPadding ( `if True, ignore files with padding length different from pattern`) I would not expect it to have an effect on the padding style, unless maybe the padding style from the match happens to be incompatible with the padding from the pattern ?

**Comment by herronelou** [comment]
Looking at https://github.com/justinfx/fileseq/blob/master/test/test_unit.py#L1450, looks like this was known and/or expected, even with strictPadding on?

**Comment by justinfx** [comment]
I believe that is the case, yes. `strictPadding` was only intended to apply to the padding size/width. You can see in the source for `findSequence(s)OnDisk` that we call `conformPadding()` and always construct sequences with "#@" padding format.

**Comment by herronelou** [comment]
do you think this can be considered a bug? I've been working on a wrapper class that wraps a FileSequence with some pathlib.Path-like methods and attributes, and when doing certain operations that call findSequenceOnPath it changes my padding which causes some other issues down the line. 
Even with strictPadding True, it should just not find the sequence if the padding is wrong, not change it ?

**Comment by justinfx** [comment]
I wouldn't specifically call it a bug, since before we introduced `strictPadding` we would have to always evaluate the actual padding of the discovered sequences and build a new padding value. So we never supported building alternate padding formats; only ever using them as parsing rules. But then we adding `strictPadding` to ensure that what you asked for in terms of the padding width would be honored. 
So that being said, it might make sense to improve on this and say that if `strictPadding` is enabled, then we could trust the original padding format, if it was actually supplied. 

```
findSequenceOnDisk("/path/to/file.$F4.ext", strictPadding=True)
"/path/to/file.1-3$F4.ext"
```

Would that solve your problem? Or do you expect it to work even if you supplied `strictPadding=False`? 

```
findSequenceOnDisk("/path/to/file.$F4.ext", strictPadding=False)
"/path/to/file.1-3$F2.ext"
```

The latter example is more complicated because then we have to support building alternate padding formats, which we currently do not.

**Comment by herronelou** [comment]
Let's take the case where my folder contains the files:
- file.01.ext
- file.02.ext
- ...
- file.99.ext
- file.100.ext
- file.101.ext

if calling `findSequenceOnDisk("file.%02d.ext", strictPadding=False)` I expect `FileSequence(file.1-101%02d.ext)`, as the pattern's padding did match what's on disk, no reason to change it.
if calling `findSequenceOnDisk("file.%03d.ext", strictPadding=False)` I expect `FileSequence(file.1-101%02d.ext)` I guess, giving a similar "style" to the padding if it knows how to. In that specific case, if it changes for some reason that might be unavoidable.
if calling `findSequenceOnDisk("file.%03d.ext", strictPadding=False)` I expect `FileSequence(file.100-101%03d.ext)`: Only finding what matches my pattern, and not changing the padding from the pattern.

**Comment by justinfx** [comment]
Ok let's take a simpler example:

```
file.1001.ext
file.1002.ext
file.1003.ext
```

This sequence can be considered 1, 2, 3, or 4 padded because the width matches in any case.

The current behaviour of fileseq is:

- `findSequenceOnDisk("file.%02d.ext", strictPadding=False)`  ->  "file.1001-1003#.ext"
- `findSequenceOnDisk("file.$F3.ext", strictPadding=False)`  ->  "file.1001-1003#.ext"
- `findSequenceOnDisk("file.%02d.ext", strictPadding=True)`  ->  "file.1001-1003@@.ext"
- `findSequenceOnDisk("file.$F3.ext", strictPadding=True)`  ->  "file.1001-1003@@@.ext"
- `findSequenceOnDisk("file.$F8.ext", strictPadding=False)`  ->  "file.1001-1003#.ext"
- `findSequenceOnDisk("file.$F8.ext", strictPadding=True)`  -> `FileSeqException: no sequence found on disk matching file.$F8.ext`

So we can see that with `strictPadding` disabled, it just uses whatever padding you give it as a placeholder and figures out what it think the padding should be. And with `strictPadding` enabled, it will need to match the padding to what is on disk, but will then represent the padding using the standard "#@" characters.

What I am suggesting is that when you specify `strictPadding=True` and it actually finds a sequence, then we know the padding you provided is correct and we could directly use that original padding character if provided. But if `strictPadding=False` then we can't be sure the original padding was right, and we have to build the padding characters. 

So if you give this:

```
findSequenceOnDisk("file.$F8.ext", strictPadding=False) 
# "file.1001-1003#.ext"
```

we cannot use the original "$F8" because we can't trust it (its not correct for this sequence), and we also don't have an implementation to build houdini (or printf) padding currently. So we would just return it as "#".  If we wanted to return "$F4" then we have to support telling `getPaddingChars()` to use different pad maps, such as printf or houdini.

**Comment by herronelou** [comment]
I can live with that, but do you think in cases it does find a sequence with the provided padding (and strictPadding=False) it could keep it?

- `findSequenceOnDisk("file.%02d.ext", strictPadding=False)` -> "file.1001-1003%02d.ext"
- `findSequenceOnDisk("file.$F3.ext", strictPadding=False)` -> "file.1001-1003$F3.ext"
- `findSequenceOnDisk("file.%02d.ext", strictPadding=True)` -> "file.1001-1003%02d.ext"
- `findSequenceOnDisk("file.$F3.ext", strictPadding=True)` -> "file.1001-1003$F3.ext"
- `findSequenceOnDisk("file.$F8.ext", strictPadding=False)` -> "file.1001-1003#.ext"
- `findSequenceOnDisk("file.$F8.ext", strictPadding=True)` -> `FileSeqException: no sequence found on disk matching file.$F8.ext`

**Comment by justinfx** [comment]
Oh right, I see what you mean now. Without digging further into the existing code, I would say it might be able to retain the original padding if the source pattern padding width is exactly equal to the discovered padding width.

**Comment by justinfx** [comment]
If we did add the feature, would you also be ok with opting into it via something like `preservePadding=True` ? Because I wouldn't want to change the existing return value for users that don't expect it and would be relying on the return value to be conformed.

**Comment by herronelou** [comment]
Yeah I don't think it's a massive massive change, I ran a debugger through the function earlier, and it starts with knowing the provided padding. Then it parses what is on disk and the glob comes back with whatever padding the glob uses, which doesn't seem to be related to the provided sequence (in my case was #), if strictPadding=False, it just returns that. If strictPadding=True, it then does replace it, but with the conformed padding.

**Comment by herronelou** [comment]
an extra arg would be fine yes

**Comment by justinfx** [comment]
@herronelou can you have a look at #114 and see if it meets your needs?
