### ISSUE TITLE
Fails if there's anything in-between frame-range and extension

### ISSUE THREAD

**Issue by MrKepzie** [justinfx/fileseq#53]
Last version of the master branch:

The fileseq.findSequenceOnDisk method has trouble finding a sequence for a file sequence such as:
    `img#_suffix.jpg`
will not be recognized. Even a single character after the frame-range specifier will make it fail, e.g:
    ` img#_.jpg`
Removing the suffix makes it work again:
    `img#.jpg`

**Comment by justinfx** [comment]
It is true that fileseq does not consider that case a valid sequence format. The stance the library has taken is that it has to establish some form of opinions about acceptable sequence formats in order to keep parsing manageable and not get into complicated logic. I am not sure if we would expand the parsing rules to accept this case. The rule in this case is that we expect frame numbers to be the last characters before the extension component. 

Is it common in pipelines to support sequences that don't follow these conventions? I have not encountered the usage of this convention at my current or previous studios.

**Comment by MrKepzie** [comment]
I understand this might not fall into the accepted formatting of filenames for some pipelines. In this case, I think it should at least be documented in the README in a *limitations* section.
