### ISSUE TITLE
Get frame ranges

### ISSUE THREAD

**Issue by asztalosdani** [justinfx/fileseq#73]
Hi,

some exporters need a start and an end frame as parameters, so I need a method that can give me a list of start-end pairs from a FrameSet.
Something like:
```
>>> f = fileseq.FrameSet("1,5,7,8,10-13,14")
>>> f.frameRanges()
[(1, 1), (5, 5), (7, 8), (10, 14)]
```
Is there a method for this?

**Comment by justinfx** [comment]
Sounds like you want to use `Filesequence.split()` to get a list of contiguous sequences. And for each of those you can get the start/end values :
https://fileseq.readthedocs.io/en/latest/#fileseq.filesequence.FileSequence.split

**Comment by asztalosdani** [comment]
Hi Justin,

I don't have files, I have only a FrameSet. 
I got something, but the `frameRange` is empty and `start`, `end` returns 0. But don't think creating a fake FileSequence is the best approach.
```python
import fileseq

frame_set = fileseq.FrameSet("1,5,7,8,10-13,14,20-80x5")
file_sequence = fileseq.FileSequence("hurrdurr")
file_sequence.setFrameSet(frame_set.normalize())

print file_sequence.frameRange()
for fs in file_sequence.split():
    print fs
    print fs.frameRange()
    print fs.start(), fs.end()
```

**Comment by justinfx** [comment]
Sorry, I had thought it was coming from a FileSequence. 
If you look at the `FileSequence.split()` source code, it is a very short method of a few lines that splits on comma and constructs the parts back into new `FileSequence` instances. So that means it would be only one line for a `FrameSet` to split:

```python
[fileseq.FrameSet(p) for p in fs.frange.split(',')]
```

And for your specific use case:

```python
for f in (fileseq.FrameSet(p) for p in fs.frange.split(',')):
    print (f[0], f[-1])
```

I'm not sure if the one line warrants another method on `FrameSet`. Is this sufficient?

**Comment by asztalosdani** [comment]
It works for simple stuff, but for `20-80x5` it isn't.

**Comment by justinfx** [comment]
I can see that for your particular case you are looking for consecutive start-stop ranges. That would be a range with a stepping of 1 or -1. The split logic breaks it into "contiguous" ranges, where a stepping value is considered to be part of that range ("20-80x5"). I'm not sure what results you would expect for something like that. "20-80x5" is contiguous by fileseq standards, but not consecutive. Are you looking for that to be represented as individual frames (`[20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]`), regardless of how big it could be, such as "1-1000x3"? 
You will need to make use of the available `FrameSet` methods to evaluate these new split parts and format them the way that suits your application needs. 

ie

```python
parts = (fileseq.FrameSet(p) for p in fs.frange.split(','))
for p in parts:
    if p.isConsecutive():
        print p[0], p[-1]
    else:
        for frame in p:
            print frame, frame

5 5
7 7
8 8
10 13
14 14
20 20
25 25
30 30
35 35
40 40
45 45
50 50
55 55
60 60
65 65
70 70
75 75
80 80

```

I'm not sure what else could be generalized as a method of `FrameSet` to help you, but I am open to suggestions.

**Comment by asztalosdani** [comment]
Thanks Justin! This is getting there what I was looking for. Yes, I need separate frames for the x5 range.
1. In the example output above, the 7 and 8 are separated. I know, I have to call `normalize()`, but why do I have to do it explicitly? I would expect `FrameSet` to always use the most compact representaion.
2. I feel like something odd is happening if we are using str.split() for this logic, while the actual frame data is already present in the `order` or `items` attributes, so it could be extracted from there. Correct me if I'm wrong.
3. I'd like to see this as a method of `FrameSet`, but if you don't see this general enough, I am fine with writing a helper method in our code.


Why do I need this? I want the user to supply a frame range in a textfield on a custom, DCC independent UI. When using this in Nuke to render Write nodes, I have to call `nuke.execute(node, start, end)`.

**Comment by yawpitch** [comment]
Nothing specific to add on the feature being described, but if it’s just for **nuke.execute** then IIRC I believe you can do this:

```python
nuke.execute(node, nuke.FrameRanges(list(FrameSet(“20-80x5”))))
```

And that _should_ render any FrameSet that is valid for that node.

**Comment by asztalosdani** [comment]
Well, I didn't know that. :)
But then again I have assExport, abcExport and who knows what else, so a more generic approch would be welcome.

**Comment by yawpitch** [comment]
Right, this should yield a new FrameSet for each consecutive range of the one passed in:

```
from itertools import zip_longest

def split_consecutive(frameset):
    curr_frames, next_frames = tee(iter(frameset))
    next(next_frames, None)
    working = []
    for curr_frame, next_frame in zip_longest(curr_frames, next_frames):
        working.append(curr_frame)
        if next_frame is None or abs(next_frame - curr_frame) != 1:
            yield FrameSet(working)
            working.clear()
```

From that you could build a list of the fs.start() and fs.end() values as required.

Note this will _not_ normalize the incoming FrameSet, for the same reason we _don't_ do so by default, we assume the person creating the FrameSet knows the order they want and is expressing it that way on purpose. If they know their order is loopy, they **FrameSet.normalize** it.

This could be trivially made a method of **FrameSet** if desired by changing **frameset** to **self** ... but honestly I'm not _entirely_ sure the need to split into _consecutive_ regions is a common one. Don't all modern DCC packages accept a first, last, and a step to render on at this point? I'd have thought the `[FrameSet(f) for f in FrameSet(INPUT).frange.split(",")]` approach mentioned by @justinfx would be sufficient because of that.

**Comment by justinfx** [comment]
On Sun, Jun 16, 2019 at 12:49 AM Daniel Asztalos <notifications@github.com>
wrote:

> Thanks Justin! This is getting there what I was looking for. Yes, I need
> separate frames for the x5 range.
>
>    1. In the example output above, the 7 and 8 are separated. I know, I
>    have to call normalize(), but why do I have to do it explicitly? I
>    would expect FrameSet to always use the most compact representaion.
>
> Michael is correct that we do not normalize the input range string
automatically so that we can allow the user to provide an explicit order to
the frames.
While you are also right that we technically could be generating a more
compact and order-preserving representation of the input range string, we
don't do any implicit string reformatting. Only the normalize function does
that. We do have a framesToFrameRange() function that accepts an iterable
of frames and converts it to a string. You could explicitely add this step
if you rely on a compact representation:

fs = fileseq.FrameSet("1,5,7,8,10-13,14,20-80x5,1,3,4")
fileseq.framesToFrameRange(fs, sort=False)
# '1,5,7-8,10-14,20-80x5,3-4'


>    1. I feel like something odd is happening if we are using str.split()
>    for this logic, while the actual frame data is already present in the
>    order or items attributes, so it could be extracted from there.
>    Correct me if I'm wrong.
>
> Splitting a string on the known comma boundaries is a lot simpler than
iterating the unrolled items, for the purpose of generating new contiguous
ranges. But you have a specialized case of just wanting the start/end of
each range and not the whole FrameSet object. So if you want, you can just
iterate the `FrameSet` instance yourself and figure out where the
boundaries start and stop.

**Comment by justinfx** [comment]
Closing - inactive
