### ISSUE TITLE
Removing cross platform tests

### ISSUE THREAD

**Issue by PaulEmileB** [justinfx/fileseq#90]
I have issues with the cross platform tests:

test_unit.TestFindSequencesOnDisk.testCrossPlatformPathSep
test_unit.TestFindSequenceOnDisk.testCrossPlatformPathSep

The tests are "mocking" os.path which breaks the behavior of os.walk on Linux (python 2.7).
Since the tests are done on both Windows and Linux, I don't see the point of keeping these tests.
Or maybe there is something I didn't grasp?

**Comment by justinfx** [comment]
The crossplatform tests were added in order to verify linux/windows path sep behaviour without needing to push changes up to a remote branch and trigger a CI to run the unit tests. Everything has seemed to be working so far. Can you show an example of what is now breaking for you? The mock happens only in that test, so it is a problem where it is breaking your new test? Or are you making new changes to findSequenceOnDisk that ends up broken by the mock?

**Comment by PaulEmileB** [comment]
Ok I understand

So far I only added sequence directories to the existing tests.
Mocking the os.path for os.ntpath changes the directory sequence path from seqsubdirs/sub1/bar0001 to seqsubdirs/sub1\\bar0001. os.stat raises a exception on the later which makes the isdir method return False on Linux.
In the end, os.walk behaves like the directories are files and it breaks the tests.

**Comment by justinfx** [comment]
Hmm ok. Maybe you should just add your test case to the `testFindSequenceOnDisk` test instead?

**Comment by justinfx** [comment]
I'm going to close this ticket since it wasn't really apparently that we should need to remove any existing tests. Just add new tests if you need to.
