### ISSUE TITLE
Missing frame token in FileSequence string representation when it has no range

### ISSUE THREAD

**Issue by UnaiM** [justinfx/fileseq#96]
HI,

If I create a `FileSequence` without specifying the frame range, or set an existing `FileSequence`’s range to the empty string, and then get its string representation, the following happens:

```python
import fileseq
seq = fileseq.FileSequence('/path/to/frames.1-5@@@.exr')
print(seq)
print(str(fileseq.FileSequence('/path/to/frames.@@@.exr')))
seq.setFrameRange('')
print(seq)
```
```
/path/to/frames.1-5@@@.exr
/path/to/frames..exr
/path/to/frames..exr
```

Is this the expected behaviour?

Thanks,
Unai

**Comment by justinfx** [comment]
I can see that the behaviour actually changed between releases 1.0.0 and 1.1.0, where the earlier behaviour was to preserve the frame padding characters in the string. And then the frame padding characters were omitted after 1.1.0. So I would probably call this a bug since it changed legacy formatting for reasons I can't recall.
We should label this as a valid bug for now and look into restoring the original formatting if the change was unintentional.

**Comment by UnaiM** [comment]
Thank you so much for the quick replies! 🎉  Maybe this change in behaviour was because of #20 ?

**Comment by justinfx** [comment]
Yes that could be a likely case. Thanks for that.

**Comment by yawpitch** [comment]
It's been a _long_ time, but as I recall the change in behavior was intentional and based on offline discussion that came up after the release of 1.0.0 around the idea that any two empty FileSequence objects with the same dirname, basename, and extension _should_ compare as equivalent in the same way that any two empty strings or two empty lists should do so.

This was one of the many, many, _many_ ambiguous and undefined behaviors around programmatic construction of file sequences that we tried to resolve by rough consensus and a hallway conversation back in the day ... I'm not entirely sure we came to the right solution, but I do remember there was discussion immediately after 1.0.0 and the question of the empty (and somewhat illogical) sequence came up and the behavior in 1.1.0 was the consensus resolution to that ambiguity.

**Comment by justinfx** [comment]
Here is what I think, after looking at the current state of things...

I see that as part of the change to fixing the handling of seq patterns with no frame number, that we adjusted the string representation logic to omit the padding characters if there is no frame range:
https://github.com/justinfx/fileseq/commit/8c7cda3572cf360d78ce5c765ff0a8b2df3ebdce#diff-a74f9ef5a186c5a701fe5eeed9b63850a79e2f5e66b8601e6e627c3dd23c6ff9R326

If we parse a single file that has a frame, we detect padding and represent it in the string format:
```python
seq = fileseq.FileSequence("/path/file.0001.ext")
str(seq)
'/path/file.0001#.ext'
``` 

If we parse a sequence pattern that has no frame range, we don't set padding and don't include any characters in the string format:
```python
seq = fileseq.FileSequence("/path/file.ext")
str(seq)
'/path/file.ext'
```

Even if we set a padding character on a pattern with no frame range, we still don't include padding:
```python
seq = fileseq.FileSequence("/path/file.ext")
seq.setPadding("#")
str(seq)
'/path/file.ext'
```

So to me it would make sense that if there is no frame range, then it doesn't make sense to include a padding character because they have no meaning in the context of a sequence pattern with no range. We effectively consider that to mean a single file. The question for me then comes down to, @UnaiM why do you feel that a sequence pattern with no frame range should still include the padding characters in the string representation? Is there a particular application where this representation is beneficial? If you have a special application for this formatting, I would suggest you take advantage of the custom `FileSequence.format()` functionality:

```python
seq = fileseq.FileSequence("/path/file.@@@.ext")
seq.format('{dirname}{basename}{range}{padding}{extension}')
'/path/file.@@@.ext'
```

This avoids the default logic that only conditionally includes the padding and lets you represent your sequence exactly the way your application expects. Is this useful for solving your issue?

**Comment by UnaiM** [comment]
Hi @yawpitch and @justinfx,

Thanks for the explanation; now I understand that, regardless of its string representation, the `FileSequence` object is always aware of where and how the frame number should be expressed, which is all I need really.

I was afraid of using `FileSequence.format('{dirname}{basename}{range}{padding}{extension}')` in case I would be assuming too much by explicitly enforcing a format, but now I see that it really is the only possible way a sequence could exist, so that solves my question :)

Cheers,
Unai

**Comment by justinfx** [comment]
Oh awesome. I'm happy to hear that asking these questions helped you to better understand the features of a FileSequence object. Glad we don't need to investigate changes!
